import React from 'react'
import SectionCode from '../components/SectionCode'
import {
  codeExamplePropsBasicOne,
  codeExamplePropsBasicTwo,
  codeExamplePropsBasicThree,
  codeExamplePropsBasicFour,
  codeExamplePropsBasicFive,
  codeExamplePropsBasicSix,
  codeExamplePropsBasicSeven,
  codeExamplePropsBasicEight,
  codeExamplePropsBasicNine,
  codeExamplePropsBasicOneDesc,
  codeExamplePropsBasicTwoDesc,
  codeExamplePropsBasicThreeDesc,
  codeExamplePropsBasicFourDesc,
  codeExamplePropsBasicFiveDesc,
  codeExamplePropsBasicSixDesc,
  codeExamplePropsBasicSevenDesc,
  codeExamplePropsBasicEightDesc,
  codeExamplePropsBasicNineDesc,
  codeExamplePropsOne,
  codeExamplePropsTwo,
  codeExamplePropsThree,
  codeExamplePropsFour,
  codeExamplePropsOneDesc,
  codeExamplePropsTwoDesc,
  codeExamplePropsThreeDesc,
  codeExamplePropsFourDesc,
} from '../codeSnippets/propsExamples'
interface PropsProps {}

const Props: React.FC<PropsProps> = () => {
  return (
    <>
      <SectionCode
        sectionID='basicOne'
        title='Basic Prop Types Examples'
        version='secondary'
        description={codeExamplePropsBasicOneDesc}
        codeExample={codeExamplePropsBasicOne}
      />
      <SectionCode
        sectionID='basicTwo'
        title=''
        version='primary'
        description={codeExamplePropsBasicTwoDesc}
        codeExample={codeExamplePropsBasicTwo}
      />
      <SectionCode
        sectionID='basicThree'
        title=''
        version='secondary'
        description={codeExamplePropsBasicThreeDesc}
        codeExample={codeExamplePropsBasicThree}
      />
      <SectionCode
        sectionID='basicFour'
        title='Objects'
        description={codeExamplePropsBasicFourDesc}
        codeExample={codeExamplePropsBasicFour}
      />
      <SectionCode
        sectionID='basicFive'
        title=''
        version='primary'
        description={codeExamplePropsBasicFiveDesc}
        codeExample={codeExamplePropsBasicFive}
      />
      <SectionCode
        sectionID='basicSix'
        title='Functions'
        description={codeExamplePropsBasicSixDesc}
        codeExample={codeExamplePropsBasicSix}
      />
      <SectionCode
        sectionID='basicSeven'
        title=''
        description={codeExamplePropsBasicSevenDesc}
        codeExample={codeExamplePropsBasicSeven}
      />
      <SectionCode
        sectionID='basicEight'
        title=''
        description={codeExamplePropsBasicEightDesc}
        codeExample={codeExamplePropsBasicEight}
      />
      <SectionCode
        sectionID='basicNine'
        title=''
        version='danger'
        description={codeExamplePropsBasicNineDesc}
        codeExample={codeExamplePropsBasicNine}
      />
      <SectionCode
        sectionID='partOne'
        title=''
        version='success'
        description={codeExamplePropsOneDesc}
        codeExample={codeExamplePropsOne}
      />
      <SectionCode
        sectionID='partTwo'
        title=''
        version='warning'
        description={codeExamplePropsTwoDesc}
        codeExample={codeExamplePropsTwo}
      />
      <SectionCode
        sectionID='partThree'
        title=''
        version='primary'
        description={codeExamplePropsThreeDesc}
        codeExample={codeExamplePropsThree}
      />
      <SectionCode
        sectionID='partFour'
        title=''
        version='secondary'
        description={codeExamplePropsFourDesc}
        codeExample={codeExamplePropsFour}
      />
    </>
  )
}
export default Props
